version: '3.7'

services:
  mac-os:
    image: sickcodes/docker-osx:ventura
    container_name: mac-os
    environment:
      - "DISPLAY=${DISPLAY:-:0.0}"
      - GENERATE_UNIQUE=true 
      - MASTER_PLIST_URL='https://raw.githubusercontent.com/sickcodes/osx-serial-generator/master/config-custom.plist'
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - 50922:10022
    devices:
      - /dev/kvm